Repository alphaville/optimization-engine, pull requests merged in 2019-06, with the labels that each got.

#48 Fix/43: Builder options to be moved to BuildConfiguration
  CHANGELOG.md
  docs/contributing.md
  open-codegen/opengen/builder/optimizer_builder.py
  open-codegen/opengen/config/build_config.py
  open-codegen/opengen/test/test.py
Labels: enhancement, python

#52 Fixed with_max_duration divergence, fixed misplaced .unwrap()
  CHANGELOG.md
  src/continuation/homotopy_optimizer.rs
  src/core/panoc/panoc_optimizer.rs
Labels: rust

#55 Fixes #53
  matlab/examples/example_open_nav.m
  matlab/helpers/casadi_generate_c_code.m
Labels: bug, matlab

#53 Cartesian product of constraints
  CHANGELOG.md
  src/constraints/cartesian_product.rs
  src/constraints/mod.rs
  src/constraints/rectangle.rs
  src/constraints/tests.rs
Labels: enhancement, rust

#51 Now with unique names in C based on solver name
  .travis.yml
  CHANGELOG.md
  open-codegen/opengen/builder/optimizer_builder.py
  open-codegen/opengen/config/build_config.py
  open-codegen/opengen/config/meta.py
  open-codegen/opengen/icasadi/Cargo.toml
  open-codegen/opengen/icasadi/build.rs
  open-codegen/opengen/icasadi/extern/icasadi.c
  open-codegen/opengen/icasadi/extern/icasadi.h
  open-codegen/opengen/icasadi/extern/icasadi_config.h
  open-codegen/opengen/icasadi/src/PLACEHOLDER
  open-codegen/opengen/icasadi/src/lib.rs
  open-codegen/opengen/templates/icasadi_config.h.template
  open-codegen/opengen/templates/icasadi_lib.rs.template
  open-codegen/opengen/templates/optimizer.rs.template
  open-codegen/opengen/templates/optimizer_build.rs.template
  open-codegen/opengen/templates/tcp_server.rs.template
  open-codegen/opengen/test/test.py
  open-codegen/opengen/test/test_2_solvers.c
Labels: enhancement, python, rust

#50 C/C++ bindings documentation
  docs/python-c.md
Labels: docs
